### PR TITLE
CRUD

### PR DESCRIPTION
**Pull request by nanatwiri**
Creation of CRUD.

### CODE REVIEW

**Review by devkinoti — COMMENTED** [review]
rename the pull request, I cant tell what CRUD_adjustment means.

**Comment by nanatwiri** [comment]
Done.

**Review by devkinoti — APPROVED** [review]

**Comment by devkinoti** [comment]
Remember to keep the number of files changed between 8 - 12.

This PR is getting a bit too big. 

Once a PR is approved, you merge it to master and update your local with the new changes, then new branch, new PR

**Comment by nanatwiri** [comment]
got it.

**Pull request merged**
